const recipesData = [

    /*========================== FRANCE ==========================*/
    {
        id: 'modal-creme-brulee',
        name: 'Crème Brûlée',
        country: 'France Dessert',
        time: {prep: '20 min', cook: '35 min', total: '5 hr'},
        description: 'Crème brûlée is now almost synonymous with the classic French restaurant dessert: a silky baked custard topped with a thin, brittle layer of caramelized sugar. Its name literally means "burnt cream" in French. France, Britain, and Spain have all claimed related custard desserts, but the French version gained the strongest cultural authority through the prestige of French restaurant and pastry traditions. What makes modern crème brûlée important is the way it expresses two central ideals of French dessert-making: the custard must be exceptionally smooth and almost bubble-free, and the sugar crust must be thin, crisp, and easy to crack with a spoon — a dramatic contrast between cold and warm, soft and brittle.',
        image: 'img/popular-1.png',
        ingredients: [
            {   img: 'img/recipe-heavy cream.png',    name: 'Heavy Cream',        desc: '500 ml   <br>    Min. 35% fat content' },
            {   img: 'img/receipe-egg.png',           name: 'Egg Yolks',          desc: '5 Large  <br>    Only use the yolks'   },
            {   img: 'img/recipe-sugar.webp',         name: 'Caster Sugar',       desc: '70 g + 25–30 g extra   <br>    For custard & caramel top' },
            {   img: 'img/recipe-Vanilla Bean.png',   name: 'Vanilla',            desc: '5 ml extract   <br>    Or half a vanilla pod'   },
            {   img: 'img/recipe-salt.png',           name: 'Salt',               desc: '1 small pinch  <br>    Balances sweetness' },
        ],
        steps: [
            'Preheat the oven to 150°C. Prepare 4 ramekins and a deep roasting pan for a water bath.',
            'Pour the heavy cream into a saucepan. Add the vanilla and salt. Heat gently until steaming with small bubbles around the edge. Do not let it boil.',
            'In a bowl, whisk the egg yolks and 70 g sugar until evenly combined and slightly lighter in colour. Do not whip in too much air.',
            'Slowly pour the hot cream into the egg yolk mixture in 3 additions, whisking constantly. This tempers the eggs and prevents curdling.',
            'Strain the custard through a fine sieve into a clean container. Let it sit for 3–5 minutes, then skim off any foam.',
            'Divide the custard evenly among the ramekins. Place the ramekins in the roasting pan. Pour hot water into the pan until it reaches halfway up the sides of the ramekins.',
            'Bake for 30–38 minutes, until the edges are set but the centres still wobble slightly like jelly.',
            'Remove from the water bath, cool to room temperature, then refrigerate for at least 4 hours.',
            'Just before serving, sprinkle a thin, even layer of sugar over each custard. Caramelise with a kitchen torch until deep amber.',
            'Let the caramel sit for 1–2 minutes so the top hardens before serving.',
        ],
    },

    {
        id: 'modal-mille-feuille',
        name: 'Mille-Feuille',
        country: 'France Dessert',
        time: { prep: '45 min', cook: '25 min', total: '3 hr 10 min' },
        description: 'Mille-feuille literally means "a thousand leaves," a name that perfectly describes its visual logic: a dessert built around layers. Usually made with alternating sheets of crisp puff pastry and pastry cream, it has long been one of the most recognizable symbols of French pâtisserie. In the English-speaking world it is often called Napoleon. Culturally, mille-feuille represents a distinctly French pastry idea — taking basic ingredients and turning them, through lamination, temperature, and technique, into a dessert defined by order, fragility, and an exquisitely controlled cross-section.',
        image: 'img/France-2.2.png',
        ingredients: [
            { name: 'Puff Pastry',      desc: '2 sheets (~500 g)    <br>    Plus icing sugar for dusting' },
            { name: 'Milk',             desc: '500 ml   <br>    For pastry cream' },
            { name: 'Egg Yolks',        desc: '4    <br>    For pastry cream' },
            { name: 'Granulated Sugar', desc: '90 g <br>    For pastry cream' },
            { name: 'Cornstarch',       desc: '35 g <br>    Thickens the cream' },
            { name: 'Unsalted Butter',  desc: '20 g <br>    Stirred in off heat' },
            { name: 'Vanilla Extract',  desc: '5 ml <br>    For pastry cream' },
            { name: 'Icing Sugar',      desc: '120 g + milk 15–20 ml    <br>    For the white glaze' },
            { name: 'Dark Chocolate',   desc: '20 g, melted <br>    For feathered pattern' },
        ],
        steps: [
            'In a bowl, whisk the egg yolks, sugar, and cornstarch until smooth.',
            'Heat the milk in a saucepan until steaming.',
            'Slowly pour the hot milk into the egg yolk mixture while whisking. Return to the saucepan.',
            'Cook over medium-low heat, stirring constantly, until the mixture thickens and becomes glossy.',
            'Remove from the heat. Stir in the butter and vanilla.',
            'Transfer the pastry cream to a shallow dish, press plastic wrap directly onto the surface, and chill for at least 2 hours.',
            'Preheat the oven to 200°C. Cut puff pastry into even rectangles. Place on lined trays covered with a second tray so it does not puff too high.',
            'Bake for 18–25 minutes until deeply golden and crisp. Cool completely.',
            'Assemble: place one pastry sheet down, pipe or spread pastry cream, add a second pastry layer, more cream, then a third pastry layer.',
            'Mix icing sugar with milk to make a thick glaze. Spread over the top. Pipe thin lines of chocolate and drag a toothpick across for the classic feathered pattern.',
            'Chill briefly before slicing with a serrated knife using a gentle sawing motion.',
        ],
    },

    {
        id: 'modal-macarons',
        name: 'Macarons',
        country: 'France Dessert',
        time: { prep: '45 min', cook: '15 min', total: '25 hr' },
        description: 'The Parisian macaron consists of two delicate almond meringue shells filled with ganache, buttercream, or jam. Its ancestor is generally traced to an Italian almond cookie from the late fifteenth century, which may have entered France through networks associated with Catherine de\' Medici. It was only in the nineteenth and twentieth centuries, especially in the Paris pastry shop tradition, that the filled double-shell version became the modern standard. The macaron is a classic example of how France transformed an imported sweet into something distinctly French through refinement, precision, colour, and luxury presentation.',
        image: 'img/France-3.webp',
        ingredients: [
            { name: 'Almond Flour',      desc: '100 g<br>Sifted fine' },
            { name: 'Icing Sugar',       desc: '100 g<br>Sifted with almond flour' },
            { name: 'Egg Whites',        desc: '70 g<br>For the shells' },
            { name: 'Granulated Sugar',  desc: '65 g<br>For meringue' },
            { name: 'Cream of Tartar',   desc: 'A pinch (optional)<br>Stabilises meringue' },
            { name: 'Food Colouring',    desc: 'Optional<br>Added near end of mixing' },
            { name: 'Dark Chocolate',    desc: '120 g<br>For ganache filling' },
            { name: 'Heavy Cream',       desc: '100 ml<br>For ganache filling' },
        ],
        steps: [
            'Sift the almond flour and icing sugar together. Discard any large coarse pieces.',
            'Place the egg whites in a clean, grease-free bowl. Beat until foamy.',
            'Add the granulated sugar in 3 additions and continue beating until the meringue forms firm peaks with a slight curve at the tip. Add food colouring if using.',
            'Add the almond flour mixture to the meringue in 2 additions. Fold and press the batter against the bowl sides (macaronage) until it flows in a thick ribbon and settles back in about 10–15 seconds.',
            'Transfer to a piping bag and pipe small circles onto lined baking trays. Tap the tray firmly to release air bubbles.',
            'Let the shells rest at room temperature for 20–45 minutes, or until the tops are dry to the touch.',
            'Preheat the oven to 145–150°C. Bake one tray at a time for 13–16 minutes, until the shells develop feet and do not shift when touched gently.',
            'Cool completely before removing from the tray.',
            'For the ganache, heat the cream until steaming and pour it over the chopped chocolate. Let sit 1 minute, then stir until smooth. Cool until pipeable.',
            'Pair shells of similar size, pipe filling onto one shell, and sandwich with another.',
            'Refrigerate the filled macarons for 24 hours to mature before serving.',
        ],
    },
    
    {
        id: 'modal-madeleines',
        name: 'Madeleines',
        country: 'France Dessert',
        time: { prep: '20 min', cook: '11 min', total: '1 hr 30 min' },
        description: 'Madeleines are small shell-shaped butter cakes that occupy a distinctive place in French culture. On one level, they are traditional tea cakes, modest and elegant. Their cultural importance was transformed by Marcel Proust, who used the madeleine in In Search of Lost Time as a trigger for involuntary memory. Because of that passage, the madeleine came to symbolise memory, time, childhood, and the emotional power of taste. It is therefore not just a small cake, but a cultural object deeply tied to French ideas of recollection, intimacy, and everyday refinement.',
        image: 'img/France-4.png',
        ingredients: [
            { name: 'Unsalted Butter',  desc: '115 g<br>Browned until nutty' },
            { name: 'Eggs',             desc: '2<br>Whole eggs' },
            { name: 'Granulated Sugar', desc: '100 g' },
            { name: 'Vanilla Extract',  desc: '5 ml' },
            { name: 'Lemon Zest',       desc: 'Zest of 1 lemon' },
            { name: 'Cake Flour',       desc: '120 g<br>Sifted' },
            { name: 'Baking Powder',    desc: '4 g' },
            { name: 'Salt',             desc: '1 small pinch' },
        ],
        steps: [
            'Melt the butter in a saucepan over low heat. Continue cooking until it turns lightly golden and smells nutty. Remove from heat and let cool until just warm.',
            'In a bowl, beat the eggs, sugar, and vanilla until the mixture becomes pale, airy, and slightly thickened.',
            'Sift together the flour, baking powder, and salt. Fold the dry ingredients into the egg mixture.',
            'Add the warm browned butter and lemon zest. Fold gently until smooth.',
            'Cover the batter and refrigerate for at least 1 hour, preferably 2 hours.',
            'Butter the madeleine mould well and dust lightly with flour. Tap out the excess.',
            'Preheat the oven to 200°C.',
            'Spoon the batter into the moulds, filling each about three-quarters full.',
            'Bake for 9–11 minutes, until the centres rise into the characteristic hump and the edges are lightly golden.',
            'Let the madeleines sit in the pan for 1 minute, then unmould onto a wire rack.',
        ],
    },

    {
        id: 'modal-canele',
        name: 'Canelé',
        country: 'France Dessert',
        time: { prep: '20 min', cook: '1 hr 10 min', total: '14 hr' },
        description: 'Canelé is one of the most regionally distinctive sweets of Bordeaux: dark, glossy, almost heavily caramelised on the outside, and soft, moist, and custardy within. Its history is often linked to the wine trade, monastic baking, and the port culture of Bordeaux. A frequently repeated explanation is that egg whites were used to clarify wine, leaving surplus yolks that convent bakers then used in sweets. At the same time, colonial trade brought sugar, vanilla, and rum into the region. Today it functions almost as an edible emblem of Bordeaux itself.',
        image: 'img/France-5.avif',
        ingredients: [
            { name: 'Whole Milk',       desc: '500 ml' },
            { name: 'Unsalted Butter',  desc: '25 g' },
            { name: 'Vanilla Extract',  desc: '5 ml' },
            { name: 'Eggs',             desc: '2 whole eggs + 2 yolks' },
            { name: 'Granulated Sugar', desc: '220 g' },
            { name: 'Plain Flour',      desc: '100 g' },
            { name: 'Dark Rum',         desc: '30 ml' },
            { name: 'Salt',             desc: '1 pinch' },
            { name: 'Butter / Beeswax', desc: 'For the moulds' },
        ],
        steps: [
            'In a saucepan, combine the milk, butter, and vanilla. Heat until almost boiling, then remove from heat and let cool until warm.',
            'In a bowl, whisk together the eggs, egg yolks, and sugar until combined. Do not whip air into the mixture.',
            'Add the flour and salt, mixing until no dry pockets remain.',
            'Gradually pour in the warm milk mixture, whisking continuously. Stir in the rum. The batter will be very thin.',
            'Strain the batter through a fine sieve. Cover and refrigerate for 12–24 hours.',
            'Before baking, let the batter sit at room temperature for 30–45 minutes and stir gently.',
            'Prepare the canelé moulds by lightly coating the interior with butter or a beeswax-butter mixture.',
            'Preheat the oven to 230°C. Fill each mould about 80–90% full.',
            'Bake for 12–15 minutes at 230°C to set the exterior, then lower to 180°C and continue baking for 45–55 minutes.',
            'The canelés should be very dark brown on the outside. Let them sit for a few minutes before unmoulding.',
        ],
        },

        {
        id: 'modal-opera-cake',
        name: 'Opera Cake',
        country: 'France Dessert',
        time: { prep: '1 hr 30 min', cook: '10 min', total: '2 hr 40 min' },
        description: 'Opera Cake is one of the most architecturally refined cakes in modern French pastry: almond sponge, coffee syrup, coffee buttercream, chocolate ganache, and a glossy chocolate glaze arranged in precise horizontal layers. Its exact authorship is disputed, with one prominent version attributing it to the Dalloyau pastry house in the 1950s. Opera Cake belongs to the world of twentieth-century urban pâtisserie — not a rustic or regional cake, but a highly composed, metropolitan dessert that reflects the sophistication of postwar Paris pastry culture. Its name is often associated with the Paris Opéra and the visual rhythm of layered seating or stage architecture.',
        image: 'img/France-6.webp',
        ingredients: [
            { name: 'Almond Flour',          desc: '120 g<br>For joconde sponge' },
            { name: 'Icing Sugar',           desc: '120 g<br>For joconde sponge' },
            { name: 'Eggs & Egg Whites',     desc: '3 whole eggs + 3 whites + 30 g sugar<br>For joconde sponge' },
            { name: 'Cake Flour + Butter',   desc: '30 g flour + 25 g melted butter<br>For joconde sponge' },
            { name: 'Coffee Syrup',          desc: '80 ml water + 60 g sugar + 6 g instant coffee<br>For soaking sponge' },
            { name: 'Coffee Buttercream',    desc: '180 g butter + 2 yolks + 60 g sugar + 15 ml coffee<br>For filling' },
            { name: 'Ganache',               desc: '150 g dark chocolate + 120 ml cream<br>For filling' },
            { name: 'Chocolate Glaze',       desc: '100 g dark chocolate + 15 g butter<br>For top layer' },
        ],
        steps: [
            'Preheat the oven to 200°C. Line a shallow baking tray.',
            'Beat the whole eggs, icing sugar, and almond flour until pale and airy.',
            'In a separate bowl, whip the egg whites with 30 g sugar until medium peaks form. Fold into the almond mixture.',
            'Sift in the cake flour and fold gently, then fold in the melted butter. Spread evenly onto the tray and bake for 8–10 minutes. Cool completely and cut into 3 equal rectangles.',
            'Make the coffee syrup by heating the water, sugar, and instant coffee until dissolved. Cool.',
            'For the ganache, heat the cream and pour it over the chopped chocolate. Stir until smooth and let it cool until spreadable.',
            'For the buttercream, cook the sugar and water into a syrup. Beat the yolks while slowly pouring in the hot syrup. Continue beating until the mixture cools, then beat in the softened butter and coffee concentrate.',
            'Assemble: place one sponge layer down and brush generously with coffee syrup. Spread with coffee buttercream.',
            'Add the second sponge, brush with syrup, and spread with ganache.',
            'Add the final sponge, brush again with syrup, and spread a thin layer of coffee buttercream. Chill for 30 minutes.',
            'Melt the chocolate and butter for the glaze. Pour over the top and spread evenly. Chill until firm before slicing with a hot knife.',
        ],
    },

    /*========================== ITALY ==========================*/
    {
        id: 'modal-tiramisu',
        name: 'Tiramisu',
        country: 'Italy Dessert',
        time: { prep: '30 min', cook: '—', total: '6 hr 30 min' },
        description: 'Tiramisu is one of the most globally successful Italian desserts, yet it is actually a relatively modern creation. Its origin is generally linked to the second half of the twentieth century, with one famous story connecting it to the restaurant Le Beccherie in Treviso. Its name is usually interpreted as "pick me up," which fits its rich combination of coffee, sugar, mascarpone, and cocoa. Culturally, tiramisu reflects a distinctly modern Italian dessert sensibility: it does not depend on elaborate decoration, but on softness, layering, and the balance of bitterness, sweetness, and creaminess.',
        image: 'img/Italy-1-Tiramisu.png',
        ingredients: [
            { name: 'Egg Yolks',       desc: '4' },
            { name: 'Granulated Sugar',desc: '80 g' },
            { name: 'Mascarpone',      desc: '500 g<br>Softened at room temperature' },
            { name: 'Heavy Cream',     desc: '250 ml<br>Whipped to soft-medium peaks' },
            { name: 'Ladyfingers',     desc: '250 g<br>Savoiardi biscuits' },
            { name: 'Strong Coffee',   desc: '300 ml, cooled<br>Or espresso' },
            { name: 'Coffee Liqueur',  desc: '20 ml (optional)<br>Or rum' },
            { name: 'Cocoa Powder',    desc: 'For dusting<br>Unsweetened' },
        ],
        steps: [
            'Brew the coffee in advance and let it cool completely. Stir in the liqueur if using.',
            'Place the egg yolks and sugar in a heatproof bowl over barely simmering water. Whisk until slightly thickened and the sugar dissolves. Remove from heat and continue whisking until cooler and paler.',
            'Add the mascarpone gradually to the egg yolk mixture and stir until smooth.',
            'In a separate bowl, whip the heavy cream to soft-medium peaks. Fold into the mascarpone mixture in 2 additions.',
            'Dip each ladyfinger quickly into the coffee, about 1 second per side. Do not soak them.',
            'Arrange a layer of dipped ladyfingers in the base of your dish.',
            'Spread half the mascarpone mixture over the biscuits.',
            'Repeat with another layer of coffee-dipped ladyfingers and the remaining mascarpone mixture.',
            'Cover and refrigerate for at least 6 hours, preferably overnight.',
            'Dust generously with cocoa powder just before serving.',
        ],
    },


    {
        id: 'modal-panna-cotta',
        name: 'Panna Cotta',
        country: 'Italy Dessert',
        time: { prep: '15 min', cook: '10 min', total: '4 hr 25 min' },
        description: 'Panna cotta, whose name simply means "cooked cream," is widely associated with Piedmont and is one of the best-known Italian cream desserts. Although it feels deeply traditional, the written record under that exact name is not especially old, making it a good example of how culinary tradition is shaped not only by ancient texts, but also by regional identity, repeated practice, and restaurant culture. Its appeal lies in restraint: very few ingredients, no visual excess, and a strong emphasis on texture — a dessert that reflects a northern Italian preference for clean flavour and elegant mouthfeel.',
        image: 'img/Italy-2-Panna Cotta.png',
        ingredients: [
            { name: 'Heavy Cream',     desc: '400 ml' },
            { name: 'Whole Milk',      desc: '100 ml' },
            { name: 'Granulated Sugar',desc: '60 g' },
            { name: 'Gelatin',         desc: '8 g sheets or powder<br>Soaked until soft' },
            { name: 'Vanilla Extract', desc: '5 ml' },
            { name: 'Mixed Berries',   desc: '150 g (optional)<br>For berry sauce' },
            { name: 'Lemon Juice',     desc: '5 ml (optional)<br>For berry sauce' },
        ],
        steps: [
            'Soak the gelatin in cold water until softened.',
            'In a saucepan, combine the cream, milk, sugar, and vanilla. Heat gently until steaming and the sugar has dissolved. Do not boil.',
            'Remove from heat. Add the softened gelatin and stir until completely dissolved.',
            'Strain the mixture into a jug.',
            'Pour into moulds or serving glasses and let cool to room temperature.',
            'Refrigerate for at least 4 hours, preferably longer, until softly set.',
            'For a berry sauce, cook the berries and sugar together over low heat until the fruit softens and the mixture thickens slightly. Stir in lemon juice and cool completely.',
            'Spoon the cooled sauce over the panna cotta before serving.',
        ],
    },

    {
        id: 'modal-torta-tenerina',
        name: 'Torta Tenerina',
        country: 'Italy Dessert',
        time: { prep: '20 min', cook: '25 min', total: '45 min' },
        description: 'Torta Tenerina is strongly associated with Ferrara and belongs to a family of dense, moist chocolate cakes that reflect a more urban, northern Italian dessert tradition. Its name suggests tenderness or softness, which accurately describes the contrast between its delicate outer surface and its rich, almost truffle-like interior. Unlike large decorated celebration cakes, it belongs more naturally to the café, pastry shop, and home table. It shows that Italian dessert culture includes a strong chocolate tradition shaped by texture and concentration rather than ornament.',
        image: 'img/Italy-3-Torta Tenerina.png',
        ingredients: [
            { name: 'Dark Chocolate',  desc: '200 g<br>Melted with butter' },
            { name: 'Unsalted Butter', desc: '100 g' },
            { name: 'Eggs',            desc: '4<br>Separated' },
            { name: 'Granulated Sugar',desc: '120 g<br>Half for yolks, half for whites' },
            { name: 'Cake Flour',      desc: '50 g<br>Sifted' },
            { name: 'Cocoa Powder',    desc: '15 g<br>Sifted' },
            { name: 'Salt',            desc: '1 small pinch' },
        ],
        steps: [
            'Preheat the oven to 175°C. Line a 20 cm round cake tin.',
            'Melt the chocolate and butter together and stir until smooth. Let cool until warm.',
            'Separate the eggs. Beat the yolks with half the sugar until smooth.',
            'In another bowl, beat the whites with the remaining sugar until they reach soft-medium peaks.',
            'Stir the chocolate mixture into the yolks.',
            'Sift in the flour, cocoa powder, and salt. Mix until combined.',
            'Fold the whipped egg whites into the batter in 3 additions.',
            'Pour into the prepared tin and smooth the surface.',
            'Bake for 22–28 minutes. The centre may still seem slightly soft, which is correct.',
            'Cool completely before unmoulding and slicing.',
        ],
    },

    {
        id: 'modal-amaretti-cookies',
        name: 'Amaretti Cookies',
        country: 'Italy Dessert',
        time: { prep: '15 min', cook: '20 min', total: '35 min' },
        description: 'Amaretti are traditional Italian almond cookies whose name comes from amaro, meaning slightly bitter — a reference to the characteristic aroma of bitter almond or apricot kernel. They exist in many forms, from crisp and dry to soft and chewy, but they all express a key Italian dessert principle: minimal ingredients, maximum identity. Unlike modern, highly stylised almond sweets such as the macaron, amaretti belong to a more humble, domestic, pantry-centred tradition. They are often eaten with coffee, stored in tins, or connected to holidays and regional baking.',
        image: 'img/Italy-4-Amaretti Cookies.png',
        ingredients: [
            { name: 'Almond Flour',      desc: '200 g<br>Fine texture' },
            { name: 'Granulated Sugar',  desc: '150 g' },
            { name: 'Egg Whites',        desc: '2<br>Lightly beaten until frothy' },
            { name: 'Almond Extract',    desc: '2–3 drops (optional)' },
            { name: 'Icing Sugar',       desc: 'For coating' },
        ],
        steps: [
            'Preheat the oven to 160°C and line a baking tray.',
            'Mix the almond flour and granulated sugar together in a bowl.',
            'Lightly beat the egg whites until frothy but not stiff.',
            'Add the egg whites gradually to the almond mixture until a soft dough forms.',
            'Add almond extract if using.',
            'Roll the dough into small balls of about 20 g each.',
            'Coat each ball lightly in icing sugar and place on the tray.',
            'Flatten slightly with your hand.',
            'Bake for 18–22 minutes, until the tops crack and the edges begin to colour.',
            'Cool fully before moving, as the cookies are delicate when hot.',
        ],
    },

    /*========================== AUSTRIA ==========================*/

    {
        id: 'modal-gugelhupf',
        name: 'Gugelhupf',
        country: 'Austria Dessert',
        time: { prep: '30 min', cook: '40 min', total: '2 hr 40 min' },
        description: 'Gugelhupf is one of the most recognizable ring cakes of Central Europe and appears across Austrian, German, and neighbouring culinary traditions. Its importance lies not only in the recipe, but in its form: the tall fluted ring mould, the dusting of sugar, and the ease with which it can be sliced and shared. In Austria especially, it fits into the broader tradition of Kaffee und Kuchen, in which cake is not merely dessert, but part of a daily social ritual involving coffee, conversation, reading, and leisure. Gugelhupf is therefore less about spectacle than about companionship and everyday elegance.',
        image: 'img/Austria-1-Gugelhupf.png',
        ingredients: [
            { name: 'Plain Flour',       desc: '350 g' },
            { name: 'Instant Yeast',     desc: '7 g' },
            { name: 'Granulated Sugar',  desc: '80 g' },
            { name: 'Salt',              desc: '4 g' },
            { name: 'Warm Milk',         desc: '180 ml' },
            { name: 'Eggs',              desc: '2' },
            { name: 'Unsalted Butter',   desc: '90 g, softened' },
            { name: 'Raisins',           desc: '80 g<br>Optionally soaked in 15 ml rum' },
            { name: 'Lemon Zest',        desc: 'Zest of 1 lemon' },
            { name: 'Icing Sugar',       desc: 'For finishing' },
        ],
        steps: [
            'If using rum, soak the raisins for 20 minutes, then drain.',
            'In a large bowl, combine the flour, yeast, sugar, and salt.',
            'Add the warm milk and eggs and mix into a dough.',
            'Add the softened butter gradually and knead until the dough becomes smooth and elastic.',
            'Knead in the raisins and lemon zest.',
            'Cover and let the dough rise until doubled in size, about 60–90 minutes.',
            'Butter and flour a ring mould.',
            'Deflate the dough gently, shape it into a log, join the ends into a ring, and place it in the mould.',
            'Let rise again until puffy and about three-quarters full in the mould.',
            'Bake at 175°C for 35–45 minutes, until golden and cooked through.',
            'Cool for 10 minutes before unmoulding. Dust with icing sugar when cool.',
        ],
    },

    {
        id: 'modal-marillenknodel',
        name: 'Marillenknödel',
        country: 'Austria Dessert',
        time: { prep: '40 min', cook: '12 min', total: '52 min' },
        description: 'Marillenknödel is a deeply seasonal Austrian dessert associated especially with summer apricots. It is unusual in that it can feel like both a dessert and a sweet main course. Apricots are wrapped in a dough made from potato or curd cheese, boiled, and then rolled in buttered breadcrumbs. This reflects a broader Central European tradition in which sweet dishes can also function as substantial meals. The Austrian word Marille for apricot already signals a regional identity, especially in areas such as the Wachau Valley. Culturally, this is a fruit-and-home-kitchen dessert strongly tied to the rhythms of harvest and family cooking.',
        image: 'img/Austria-2-Marillenknoedel.webp',
        ingredients: [
            { name: 'Potatoes',         desc: '500 g<br>Boiled, peeled, mashed' },
            { name: 'Unsalted Butter',  desc: '30 g' },
            { name: 'Egg Yolk',         desc: '1' },
            { name: 'Plain Flour',      desc: '~120 g<br>Enough for a soft dough' },
            { name: 'Salt',             desc: '1 pinch' },
            { name: 'Apricots',         desc: '8 small<br>Pitted, filled with sugar' },
            { name: 'Sugar Cubes',      desc: '8<br>One per apricot' },
            { name: 'Breadcrumbs',      desc: '80 g<br>Toasted in 40 g butter' },
            { name: 'Cinnamon Sugar',   desc: '25 g sugar + a little cinnamon<br>For coating' },
        ],
        steps: [
            'Boil the potatoes in their skins until tender. Peel while still warm and mash.',
            'Spread the mashed potatoes out and let them cool until warm, not hot.',
            'Mix in the butter, egg yolk, and salt. Add enough flour to make a soft dough that is no longer sticky.',
            'Wash the apricots. Cut each open along one side and remove the pit. Insert a sugar cube or spoonful of sugar and close the fruit.',
            'Divide the dough into 8 pieces. Flatten each piece and wrap it around an apricot, sealing the dough completely.',
            'Bring a large pot of water to a gentle simmer, not a hard boil.',
            'Add the dumplings and stir gently once so they do not stick.',
            'Simmer for 10–12 minutes, until they float, then cook 1–2 minutes more.',
            'Meanwhile, melt the butter in a pan. Add the breadcrumbs and toast until golden. Stir in the sugar and cinnamon.',
            'Drain the dumplings and roll them in the breadcrumb mixture while still warm.',
        ],
    },

    {
        id: 'modal-mozartkugeln',
        name: 'Mozartkugeln',
        country: 'Austria Dessert',
        time: { prep: '45 min', cook: '—', total: '1 hr 15 min' },
        description: 'Mozartkugeln are among Salzburg\'s most successful edible symbols. They combine confectionery, tourism, urban identity, and musical heritage in a single product. Named after Mozart and often wrapped in gleaming foil, they are as much souvenirs as sweets. Traditional versions combine pistachio, marzipan, and chocolate, producing a flavour profile that is distinctly Central European in its richness and nut-based sweetness. Their cultural significance extends beyond taste: they are part of the city\'s self-presentation as the home of Mozart and a centre of classical music.',
        image: 'img/Austria-3-mozartkugel.png',
        ingredients: [
            { name: 'Pistachio Meal',   desc: '80 g<br>Very finely ground pistachios' },
            { name: 'Almond Flour',     desc: '80 g' },
            { name: 'Icing Sugar',      desc: '100 g' },
            { name: 'Egg White',        desc: '1' },
            { name: 'Marzipan',         desc: '120 g<br>Divided into ~20 small balls' },
            { name: 'Dark Chocolate',   desc: '180 g<br>For dipping' },
        ],
        steps: [
            'Mix the pistachio meal, almond flour, and icing sugar.',
            'Add the egg white and stir until a moldable paste forms. Adjust with a little more sugar or a few drops of water if necessary.',
            'Divide the marzipan into about 20 small balls.',
            'Flatten portions of the pistachio paste and wrap each around a marzipan ball. Roll smooth.',
            'Chill the balls for 20–30 minutes.',
            'Melt the dark chocolate gently.',
            'Dip each ball into the chocolate using a fork or dipping tool.',
            'Place on baking paper and let set completely.',
        ],
    },

    {
        id: 'modal-linzer-augen',
        name: 'Linzer Augen',
        country: 'Austria Dessert',
        time: { prep: '20 min', cook: '12 min', total: '1 hr 32 min' },
        description: 'Linzer Augen can be understood as a biscuit form of the famous Linzer Torte. Two nutty, spiced cookies are sandwiched with jam, and the top one has a small cutout "eye" that reveals the red filling underneath. Their connection to Linz and to the broader Linzer pastry family is culturally significant, because Linzer Torte is often described as one of the earliest cakes named after a city. Linzer Augen inherit the same flavour profile — nuts, spices, fruit preserve — but translate it into a more domestic, portable, and gift-friendly form. They also fit strongly into the Central European Christmas cookie tradition.',
        image: 'img/Austria-4-Linzer Augen.png',
        ingredients: [
            { name: 'Unsalted Butter',  desc: '150 g, softened' },
            { name: 'Icing Sugar',      desc: '80 g' },
            { name: 'Egg Yolk',         desc: '1' },
            { name: 'Plain Flour',      desc: '220 g' },
            { name: 'Almond Flour',     desc: '50 g' },
            { name: 'Cinnamon',         desc: '½ tsp' },
            { name: 'Lemon Zest',       desc: 'A little' },
            { name: 'Salt',             desc: '1 pinch' },
            { name: 'Raspberry Jam',    desc: '120 g<br>Or red currant jam' },
        ],
        steps: [
            'Cream the butter and icing sugar until smooth.',
            'Mix in the egg yolk.',
            'Add the plain flour, almond flour, cinnamon, lemon zest, and salt. Mix into a dough.',
            'Flatten the dough into a disc, wrap, and chill for 1 hour.',
            'Preheat the oven to 175°C.',
            'Roll the dough to about 3 mm thick. Cut out an even number of rounds. Cut small holes in half of them.',
            'Bake for 10–12 minutes, until the edges are just lightly golden.',
            'Cool completely.',
            'Spread jam on the whole rounds and top with the cutout rounds.',
            'Dust with icing sugar.',
        ],
    },

    /*========================== JAPAN ==========================*/

    {
        id: 'modal-japanese-cheesecake',
        name: 'Japanese Cheesecake',
        country: 'Japan Dessert',
        time: { prep: '30 min', cook: '65 min', total: '1 hr 35 min' },
        description: 'Japanese cheesecake is a classic example of how a Western dessert was transformed through Japanese culinary aesthetics. Rather than simply copying European or American cheesecake, Japan developed a lighter, less sweet, more airy version, often closer in texture to a soufflé. This adaptation reflects a broader pattern in modern Japanese sweets: imported recipes are reworked to suit local preferences for delicacy, balance, and softness. Japanese cheesecake is therefore not just a cheesecake made in Japan, but a reinterpretation that reveals how foreign desserts are absorbed and redefined within Japanese taste culture.',
        image: 'img/Japan-1-Cheesecake.png',
        ingredients: [
            { name: 'Cream Cheese',     desc: '200 g' },
            { name: 'Milk',             desc: '100 ml' },
            { name: 'Unsalted Butter',  desc: '40 g' },
            { name: 'Egg Yolks',        desc: '4' },
            { name: 'Cake Flour',       desc: '50 g<br>Sifted' },
            { name: 'Cornstarch',       desc: '15 g<br>Sifted' },
            { name: 'Egg Whites',       desc: '4<br>For meringue' },
            { name: 'Granulated Sugar', desc: '80 g<br>For meringue' },
            { name: 'Lemon Juice',      desc: '5 ml<br>Stabilises whites' },
        ],
        steps: [
            'Line the base of a 6-inch round tin and wrap the outside in foil to protect it in a water bath.',
            'Preheat the oven to 150°C.',
            'Heat the cream cheese, milk, and butter together over a bain-marie until smooth.',
            'Remove from heat and whisk in the egg yolks one at a time.',
            'Sift in the cake flour and cornstarch and whisk until smooth.',
            'In another bowl, beat the egg whites with lemon juice until foamy. Add the sugar gradually and continue beating until soft-medium peaks form.',
            'Fold one-third of the meringue into the cheese batter to lighten it.',
            'Fold the lightened batter into the remaining meringue in 2 additions.',
            'Pour into the prepared tin and tap lightly to remove large bubbles.',
            'Place the tin in a deep tray and pour hot water around it.',
            'Bake for 55–65 minutes, until lightly golden and gently set.',
            'Turn off the oven, open the door slightly, and let the cake rest inside for 15 minutes.',
            'Cool completely and chill before slicing.',
        ],
    },

    {
        id: 'modal-dorayaki',
        name: 'Dorayaki',
        country: 'Japan Dessert',
        time: { prep: '15 min', cook: '20 min', total: '35 min' },
        description: 'Dorayaki is one of the most familiar and approachable Japanese sweets. It belongs to the broad wagashi tradition, but unlike highly ceremonial tea sweets, it is an everyday, widely loved treat. Two soft pancake-like cakes sandwich sweet red bean paste, making it a very direct expression of Japan\'s long relationship with sweet bean fillings. Its round shape is often associated with a gong or drum, and in popular culture it became even more iconic through its connection with the character Doraemon. Dorayaki represents not formal sophistication, but warmth, accessibility, and the enduring popularity of red bean-based sweets in Japanese food culture.',
        image: 'img/Japan-2-Dorayaki.avif',
        ingredients: [
            { name: 'Eggs',              desc: '2' },
            { name: 'Granulated Sugar',  desc: '70 g' },
            { name: 'Honey',             desc: '15 g' },
            { name: 'Milk',              desc: '40 ml' },
            { name: 'Plain Flour',       desc: '120 g<br>Sifted' },
            { name: 'Baking Powder',     desc: '4 g' },
            { name: 'Red Bean Paste',    desc: '240 g<br>Sweet anko paste' },
            { name: 'Oil',               desc: 'A little<br>For the pan' },
        ],
        steps: [
            'Whisk the eggs, sugar, and honey together until the sugar dissolves and the mixture becomes slightly lighter.',
            'Stir in the milk.',
            'Sift in the flour and baking powder and mix until smooth.',
            'Let the batter rest for 15 minutes.',
            'Heat a non-stick pan over low heat. Lightly oil it, then wipe away the excess.',
            'Spoon small rounds of batter onto the pan.',
            'Cook until bubbles appear evenly across the surface, then flip and cook for 20–30 seconds more.',
            'Cool the cakes completely.',
            'Pair them by size and sandwich with red bean paste.',
            'Wrap loosely and let rest for 30 minutes if you want the cakes to soften further.',
        ],
    },

    {
        id: 'modal-japanese-pudding',
        name: 'Japanese Pudding',
        country: 'Japan Dessert',
        time: { prep: '20 min', cook: '35 min', total: '3 hr 55 min' },
        description: 'Japanese purin is a localised version of Western caramel custard pudding. It is related to crème caramel, but in Japan it developed its own identity through home cooking, café culture, and eventually convenience-store desserts. It is a good example of yōgashi — Western-style sweets adapted into Japanese life. Purin is usually firmer and more regular in appearance than some European versions, with a very clean sweetness and smooth texture. Its cultural role is that of a comforting, familiar, modern classic rather than a traditional wagashi.',
        image: 'img/Japan-3-Pudding.png',
        ingredients: [
            { name: 'Granulated Sugar', desc: '60 g total<br>40 g for caramel, 20 g for custard' },
            { name: 'Hot Water',        desc: '20 ml<br>For caramel' },
            { name: 'Milk',             desc: '300 ml' },
            { name: 'Eggs',             desc: '3' },
            { name: 'Vanilla Extract',  desc: '3 ml' },
        ],
        steps: [
            'Make the caramel first. Put 40 g sugar in a saucepan and heat until it melts and turns amber.',
            'Carefully add the hot water and stir. Pour immediately into the base of 4 pudding cups.',
            'Heat the milk with the remaining 20 g sugar until warm and the sugar dissolves. Do not boil.',
            'Beat the eggs lightly, without adding too much air.',
            'Slowly pour the warm milk into the eggs while stirring gently.',
            'Add the vanilla and strain the mixture once or twice.',
            'Pour into the prepared cups. Remove any surface bubbles with kitchen paper.',
            'Place the cups in a roasting tray. Pour in hot water to form a water bath.',
            'Bake at 150°C for 30–35 minutes, or steam gently until just set.',
            'Cool, then refrigerate for at least 3 hours before serving.',
        ],
    },

    {
        id: 'modal-castella',
        name: 'Castella',
        country: 'Japan Dessert',
        time: { prep: '20 min', cook: '45 min', total: '13 hr' },
        description: 'Castella is one of the clearest examples of a foreign cake becoming deeply rooted in Japanese culture. Its history is connected to Nagasaki, which served as a major site of international exchange in early modern Japan. Through Portuguese and other overseas contacts, cake traditions entered the region and were gradually adapted into what became Japanese castella. Over time, the recipe, texture, and cultural meaning shifted enough that castella became a distinctly Japanese confection, often associated specifically with Nagasaki. It is therefore more than a sponge cake: it is an edible record of trade, exchange, and the localisation of imported foods.',
        image: 'img/Japan-4-Castella.png',
        ingredients: [
            { name: 'Eggs',             desc: '4' },
            { name: 'Granulated Sugar', desc: '120 g' },
            { name: 'Honey',            desc: '30 g' },
            { name: 'Milk',             desc: '30 ml' },
            { name: 'Bread Flour',      desc: '120 g<br>Sifted' },
        ],
        steps: [
            'Line an 18 × 18 cm square tin with baking paper.',
            'Preheat the oven to 160°C.',
            'Mix the honey and milk together.',
            'Beat the eggs and sugar over a warm bain-marie until thick, pale, and able to hold ribbons.',
            'Sift in the flour in 2 additions and fold gently.',
            'Add the honey-milk mixture and fold until smooth.',
            'Pour into the tin and tap lightly to remove large bubbles.',
            'Bake for 40–50 minutes. Cover loosely with foil if the top browns too quickly.',
            'Remove from the oven and tap the tin once to release steam.',
            'Cool, then wrap well and let rest overnight before slicing.',
        ],
    },

    {
        id: 'modal-daifuku',
        name: 'Daifuku',
        country: 'Japan Dessert',
        time: { prep: '20 min', cook: '15 min', total: '35 min' },
        description: 'Daifuku is one of the most recognizable forms of wagashi, or traditional Japanese confectionery. A soft mochi wrapper encloses a sweet filling such as red bean paste, fruit, or other seasonal ingredients. Its importance lies in how clearly it expresses the values of wagashi: softness, tactility, seasonal variation, and the relationship between humble ingredients and careful handwork. Modern versions such as strawberry daifuku also show that wagashi is not frozen in the past, but continues to evolve with contemporary taste and presentation.',
        image: 'img/Japan-5-Daifuku.png',
        ingredients: [
            { name: 'Glutinous Rice Flour', desc: '150 g' },
            { name: 'Granulated Sugar',     desc: '45 g' },
            { name: 'Water',                desc: '180 ml' },
            { name: 'Cornstarch',           desc: 'For dusting' },
            { name: 'Red Bean Paste',       desc: '240 g<br>Sweet anko, divided into 8' },
            { name: 'Strawberries',         desc: '8 (optional)<br>Dried and wrapped in bean paste' },
        ],
        steps: [
            'Divide the red bean paste into 8 portions. If using strawberries, dry them well and wrap each one in a portion of bean paste.',
            'Mix the glutinous rice flour, sugar, and water until smooth.',
            'Cover loosely and microwave for 2 minutes. Stir, microwave for another minute, stir again, then microwave for 30–60 seconds more until fully cooked and translucent. Alternatively, steam until cooked through.',
            'Dust the work surface generously to prevent sticking.',
            'Turn out the mochi dough and let it cool just enough to handle.',
            'Divide into 8 pieces.',
            'Flatten each piece and wrap it around the bean paste filling. Pinch the seam closed and place seam-side down.',
            'Brush off excess starch before serving.',
        ],
    },

    {
        id: 'modal-dango',
        name: 'Dango',
        country: 'Japan Dessert',
        time: { prep: '15 min', cook: '15 min', total: '30 min' },
        description: 'Dango is another essential rice-based Japanese sweet, but it is more rustic and strongly tied to seasonal and festive settings. Skewered rice dumplings appear in street food, shrine fairs, and seasonal customs such as spring flower viewing. Dango is therefore significant not because it is luxurious, but because it is embedded in ritual, place, and shared public life. It expresses the centrality of rice in Japanese food culture beyond plain cooked rice itself, showing how grain is transformed into sweets that participate in the cycle of festivals and seasons.',
        image: 'img/Japan-6-dango.png',
        ingredients: [
            { name: 'Rice Flour',        desc: '150 g<br>Non-glutinous (joshinko)' },
            { name: 'Glutinous Rice Flour', desc: '50 g' },
            { name: 'Warm Water',        desc: '150–170 ml' },
            { name: 'Soy Sauce',         desc: '15 ml<br>For sweet soy glaze' },
            { name: 'Granulated Sugar',  desc: '40 g<br>For glaze' },
            { name: 'Water',             desc: '60 ml<br>For glaze' },
            { name: 'Cornstarch',        desc: '5 g<br>For glaze' },
        ],
        steps: [
            'Mix the two flours together in a bowl.',
            'Add the warm water gradually, kneading until a smooth dough forms that does not crack.',
            'Divide the dough into small even portions and roll into balls.',
            'Bring a pot of water to the boil, then lower to medium heat.',
            'Add the dumplings and cook until they float. Continue cooking for 2–3 more minutes.',
            'Transfer to cold water briefly, then drain well.',
            'Thread 3–4 dumplings onto each skewer.',
            'For the glaze, combine the soy sauce, sugar, water, and cornstarch in a small pan. Heat until slightly thickened.',
            'Brush the glaze over the skewered dumplings.',
            'If desired, grill or toast the skewers briefly before or after glazing for extra aroma.',
        ],
    },

    /*========================== AMERICA ==========================*/

    {
        id: 'modal-apple-pie',
        name: 'Apple Pie',
        country: 'America Dessert',
        time: { prep: '45 min', cook: '1 hr', total: '5 hr 45 min' },
        description: 'Apple pie is often treated as a symbol of American identity, yet its roots lie in Europe rather than the United States. The earliest recorded apple pie recipe appears in medieval England. What matters culturally is what happened after the pie migrated to North America: over time it became attached to ideas of home, harvest, family, patriotism, and national belonging. Expressions such as "as American as apple pie" are the result of this symbolic transformation. Apple pie therefore represents not a purely American invention, but a European dessert that was reinterpreted so thoroughly in the United States that it came to stand for Americanness itself.',
        image: 'img/America-1-Apple Pie.png',
        ingredients: [
            { name: 'Plain Flour',       desc: '315 g<br>For pie dough' },
            { name: 'Cold Butter',       desc: '225 g<br>Cut into the flour' },
            { name: 'Ice Water',         desc: '90–120 ml<br>For pie dough' },
            { name: 'Apples',            desc: '900 g<br>Peeled and sliced' },
            { name: 'Granulated Sugar',  desc: '120 g + 30 g brown sugar<br>For filling' },
            { name: 'Cornstarch',        desc: '25 g<br>Thickens the filling' },
            { name: 'Cinnamon',          desc: '1 tsp' },
            { name: 'Lemon Juice',       desc: '15 ml' },
            { name: 'Butter',            desc: '15 g<br>Dotted over filling' },
        ],
        steps: [
            'Combine the flour, salt, and sugar. Cut in the cold butter until the mixture resembles coarse crumbs with some pea-sized pieces.',
            'Add the ice water gradually until the dough just comes together.',
            'Divide into 2 discs, wrap, and chill for at least 1 hour.',
            'Mix the sliced apples with the granulated sugar, brown sugar, cornstarch, cinnamon, and lemon juice.',
            'Preheat the oven to 200°C.',
            'Roll out one disc of dough and line a 9-inch pie dish.',
            'Fill with the apple mixture and dot with butter.',
            'Roll out the second disc and place over the top, or make a lattice. Seal and crimp the edges. Cut vents if using a full top crust.',
            'Bake for 20 minutes, then reduce the oven to 180°C and bake for 35–45 minutes more, until the crust is deeply golden and the filling bubbles.',
            'Cool for at least 3 hours before slicing.',
        ],
    },

    {
        id: 'modal-brownies',
        name: 'Chocolate Brownies',
        country: 'America Dessert',
        time: { prep: '15 min', cook: '25 min', total: '40 min' },
        description: 'Brownies are widely regarded as a quintessential American sweet, and one of the best-known origin stories links them to the 1893 Chicago World\'s Fair, where a rich chocolate dessert was created at the Palmer House Hotel as a compact, elegant treat suitable for fairgoers. Brownies clearly belong to the culture of modern American hotels, urban dining, and convenience-oriented sweets. They occupy a space between cake and cookie, combining portability with richness. This in-between quality is part of what made them so successful in American food culture.',
        image: 'img/America-2-Brownie.png',
        ingredients: [
            { name: 'Unsalted Butter',   desc: '115 g' },
            { name: 'Dark Chocolate',    desc: '120 g' },
            { name: 'Granulated Sugar',  desc: '180 g' },
            { name: 'Eggs',              desc: '2' },
            { name: 'Vanilla Extract',   desc: '5 ml' },
            { name: 'Cocoa Powder',      desc: '20 g<br>Sifted' },
            { name: 'Plain Flour',       desc: '75 g<br>Sifted' },
            { name: 'Salt',              desc: '2 g' },
            { name: 'Chocolate Chips',   desc: '60 g (optional)' },
        ],
        steps: [
            'Preheat the oven to 175°C. Line an 8-inch square tin.',
            'Melt the butter and dark chocolate together and stir until smooth.',
            'Mix in the sugar.',
            'Add the eggs and vanilla and stir until glossy.',
            'Sift in the cocoa powder, flour, and salt. Fold until just combined.',
            'Stir in the chocolate chips if using.',
            'Spread the batter evenly in the prepared tin.',
            'Bake for 22–28 minutes, until the top is crackly and a skewer inserted in the centre comes out with moist crumbs, not wet batter.',
            'Cool completely before slicing.',
        ],
    },

    {
        id: 'modal-chocolate-chip-cookie',
        name: 'Chocolate Chip Cookies',
        country: 'America Dessert',
        time: { prep: '15 min', cook: '12 min', total: '1 hr 27 min' },
        description: 'The chocolate chip cookie has one of the clearest origin stories in American baking. It is generally credited to Ruth Graves Wakefield, who created it in the 1930s at the Toll House Restaurant in Massachusetts. What began as a local recipe quickly became a national phenomenon through its connection to Nestlé, the industrial production of chocolate chips, wartime sharing, and postwar convenience baking. It is therefore not only a beloved homemade cookie, but also a product deeply tied to American food industry history, branding, and domestic life. Few desserts better represent the idea of everyday comfort in American baking.',
        image: 'img/America-3-Chocolate Chip Cookie.png',
        ingredients: [
            { name: 'Unsalted Butter',   desc: '115 g, softened' },
            { name: 'Brown Sugar',       desc: '120 g' },
            { name: 'Granulated Sugar',  desc: '60 g' },
            { name: 'Egg',               desc: '1' },
            { name: 'Vanilla Extract',   desc: '5 ml' },
            { name: 'Plain Flour',       desc: '190 g' },
            { name: 'Cornstarch',        desc: '8 g<br>Keeps cookies soft' },
            { name: 'Baking Soda',       desc: '4 g' },
            { name: 'Salt',              desc: '3 g' },
            { name: 'Chocolate Chips',   desc: '180 g' },
        ],
        steps: [
            'Cream the butter, brown sugar, and granulated sugar until light and smooth.',
            'Beat in the egg and vanilla.',
            'In another bowl, whisk together the flour, cornstarch, baking soda, and salt.',
            'Add the dry ingredients to the butter mixture and mix just until combined.',
            'Stir in the chocolate chips.',
            'Chill the dough for at least 1 hour.',
            'Preheat the oven to 180°C.',
            'Portion the dough into balls of about 40–45 g each and place on lined trays.',
            'Bake for 10–12 minutes, until the edges are set but the centres still look slightly soft.',
            'Let the cookies cool on the tray for 5 minutes before transferring to a rack.',
        ],
    },

    {
        id: 'modal-new-york-cheesecake',
        name: 'New York Cheesecake',
        country: 'America Dessert',
        time: { prep: '30 min', cook: '65 min', total: '9 hr 35 min' },
        description: 'Cheesecake as a broad category has ancient roots, but New York cheesecake is a distinctly modern urban development. What sets it apart is its use of cream cheese, its dense and rich body, and its strong association with restaurant and deli culture in New York. It reflects the convergence of European cheesecake traditions with American ingredients, immigrant foodways, and metropolitan dessert habits. New York cheesecake represents a specifically twentieth-century American standard of indulgence: thick, rich, smooth, and unmistakably tied to the city\'s culinary identity.',
        image: 'img/America-4-New York Cheesecake.png',
        ingredients: [
            { name: 'Graham Cracker Crumbs', desc: '180 g<br>Or digestive biscuits' },
            { name: 'Melted Butter',    desc: '70 g<br>For crust' },
            { name: 'Cream Cheese',     desc: '680 g<br>Room temperature' },
            { name: 'Granulated Sugar', desc: '180 g (+ 20 g for crust)' },
            { name: 'Sour Cream',       desc: '180 g' },
            { name: 'Eggs',             desc: '3<br>Room temperature' },
            { name: 'Vanilla Extract',  desc: '5 ml' },
            { name: 'Lemon Juice',      desc: '10 ml' },
            { name: 'Cornstarch',       desc: '10 g' },
        ],
        steps: [
            'Preheat the oven to 160°C. Wrap the outside of an 8-inch springform tin with foil.',
            'Mix the crust ingredients and press firmly into the base of the tin. Bake for 8–10 minutes and let cool.',
            'Beat the cream cheese until smooth.',
            'Add the sugar and beat until combined.',
            'Mix in the sour cream, vanilla, lemon juice, and cornstarch.',
            'Add the eggs one at a time, mixing on low speed just until incorporated.',
            'Pour the filling over the crust and smooth the top.',
            'Place the tin in a water bath if desired and bake for 55–70 minutes, until the edges are set and the centre still wobbles slightly.',
            'Turn off the oven and leave the cheesecake inside with the door slightly open for 20 minutes.',
            'Cool to room temperature, then chill for at least 6 hours, preferably overnight.',
        ],
    },

    {
        id: 'modal-pecan-pie',
        name: 'Pecan Pie',
        country: 'America Dessert',
        time: { prep: '30 min', cook: '50 min', total: '1 hr 20 min' },
        description: 'Pecan pie is one of the most recognizable desserts of the American South. Although often perceived as old-fashioned and traditional, it is actually a relatively modern pie, shaped by cookbook culture, church suppers, family holidays, and the spread of corn syrup in twentieth-century American kitchens. Its significance lies partly in the pecan itself — a nut native to North America — which gives the pie a strong connection to southern agriculture and regional identity. It is not simply a sweet pie, but a dessert tied to Thanksgiving, gatherings, and the idea of a distinctly southern table.',
        image: 'img/America-5-Pecan Pie.png',
        ingredients: [
            { name: 'Pie Crust',         desc: '1 single crust<br>Chilled in 9-inch pie dish' },
            { name: 'Pecans',            desc: '220 g' },
            { name: 'Eggs',              desc: '3' },
            { name: 'Corn Syrup',        desc: '180 ml' },
            { name: 'Brown Sugar',       desc: '100 g' },
            { name: 'Melted Butter',     desc: '45 g' },
            { name: 'Vanilla Extract',   desc: '5 ml' },
            { name: 'Salt',              desc: '1 pinch' },
        ],
        steps: [
            'Line a 9-inch pie dish with the pie crust and chill while preparing the filling.',
            'Preheat the oven to 175°C.',
            'Whisk together the eggs, corn syrup, brown sugar, melted butter, vanilla, and salt.',
            'Arrange the pecans in the pie shell.',
            'Pour the filling over the pecans.',
            'Bake for 45–55 minutes, until the edges are set and the centre still has a slight wobble.',
            'If the crust browns too quickly, cover the edges with foil.',
            'Cool completely before slicing so the filling can finish setting.',
        ],
    },

    {
        id: 'modal-red-velvet-cake',
        name: 'Red Velvet Cake',
        country: 'America Dessert',
        time: { prep: '30 min', cook: '32 min', total: '1 hr 22 min' },
        description: 'Red velvet cake has a more layered history than its bold appearance suggests. The "velvet" part originally referred to the fine, soft crumb of certain nineteenth-century cakes. Over time, cocoa, acidic ingredients, and eventually food colouring helped create the distinctive reddish tone now associated with the cake. In the twentieth century it became more widely popular through hotels, department-store baking, and mass-market food products. It also entered important celebratory and community contexts in American life, especially in the South and in African American culinary traditions.',
        image: 'img/America-6-Red Velvet Cake.png',
        ingredients: [
            { name: 'Plain Flour',           desc: '300 g' },
            { name: 'Cocoa Powder',          desc: '15 g' },
            { name: 'Baking Soda + Salt',    desc: '5 g baking soda + 3 g salt' },
            { name: 'Unsalted Butter',       desc: '115 g, softened' },
            { name: 'Granulated Sugar',      desc: '300 g' },
            { name: 'Eggs + Oil',            desc: '2 eggs + 60 ml vegetable oil' },
            { name: 'Buttermilk + Vinegar',  desc: '240 ml buttermilk + 5 ml white vinegar' },
            { name: 'Red Food Colouring',    desc: 'As needed' },
            { name: 'Cream Cheese Frosting', desc: '300 g cream cheese + 100 g butter + 180–220 g icing sugar + 5 ml vanilla' },
        ],
        steps: [
            'Preheat the oven to 175°C. Grease and line two 8-inch round tins.',
            'Sift together the flour, cocoa powder, baking soda, and salt.',
            'Beat the butter and sugar until light and fluffy.',
            'Add the eggs one at a time, then beat in the oil, vanilla, and food colouring.',
            'Stir the buttermilk and vinegar together.',
            'Add the dry ingredients and buttermilk alternately to the batter, beginning and ending with the dry ingredients. Mix only until smooth.',
            'Divide the batter between the tins.',
            'Bake for 28–35 minutes, until a skewer inserted in the centre comes out with a few moist crumbs.',
            'Cool the cakes completely.',
            'For the frosting, beat the cream cheese and butter until smooth. Add the icing sugar gradually, then add the vanilla.',
            'Fill and frost the cooled cake.',
        ],
    },



]
